CREATE DATABASE users;

\c users;

CREATE TABLE IF NOT EXISTS users_table (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_name VARCHAR(255), 
    password VARCHAR(255), 
    user_info VARCHAR(255)
);

