/**

go mod init main
go get github.com/lib/pq
*/
package sql_connector

import (
    "database/sql"
    //"time"
    "fmt"
    //"reflect"
    _ "github.com/lib/pq"
)

type data struct {
    id int
    user_name string
    password string
    user_info string
}

var db *sql.DB
var connectString string = "postgres://postgres:USPEH@postgres:5432/users?sslmode=disable"

func CreateNewSQLConnector() {
    //connectString := "postgres://postgres:USPEH@postgres:5432/users?sslmode=disable"
    //connStr := "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
    
    d, err := sql.Open("postgres", connectString)
    if err != nil {
        panic(err)
    } 
    db = d

    _, err2 := db.Exec(`
    CREATE TABLE IF NOT EXISTS users_table (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        user_name VARCHAR(255), 
        password VARCHAR(255), 
        user_info VARCHAR(255)
    );`)

    if err2 != nil {
        fmt.Println("Error: can not add new user")
        panic(err)
    }
} 

// Создание таблицы с пользователями 
func CreateUsersTableInDatabase() {
    _, err := db.Exec(
    `CREATE TABLE IF NOT EXISTS users_table (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        user_name VARCHAR(255), 
        password VARCHAR(255), 
        user_info VARCHAR(255)
    );`)

    if err != nil {
        fmt.Println("Error: can not create database")
        panic(err)
    }
}

// Добаление нового пользователя
func AddData(userName, password, userInfo string) {
    _, err := db.Exec("INSERT INTO users_table (user_name, password, user_info) VALUES ($1, $2, $3)", userName, password, userInfo)
    if err != nil {
        fmt.Println("Error: can not add new user")
        panic(err)
    }
}

// Удаление данных
func RemoveData(userName string) {
    _, err := db.Exec("delete from users_table where user_name=$1", userName)
    if err != nil {
        fmt.Println("Error: can not delele user")
        panic(err)
    }
}

// Чтение пользовательской информации
func ReadUserInfo(userName string) string {
    result := ""
    rows, err := db.Query("SELECT user_info FROM users_table WHERE user_name=$1", userName)

    if err != nil {
        fmt.Println("Error: can read table")
        panic(err)
    }

    rows.Next()

    err2 := rows.Scan(&result)
    if err2 != nil{
	    //panic(err2)
        return ""
    }
    
    return result
}
/*
func main() {
    connStr := "user=postgres password=USPEH dbname=users sslmode=disable"
    db, err := sql.Open("postgres", connStr)
    if err != nil {
        panic(err)
    } 
    
    defer db.Close()
    
    //RemoveData("test_user_name", db)
    //AddData("user_babaika", "pass", "game", db)
    fmt.Println(ReadUserInfo("user_babaika"))
    
    /*
    // Добавление данных
    result, err := db.Exec("insert into users_table (user_name, password, user_info) values ('test_user_name', 'test_password', 'test_user_info');")
    if err != nil {
        panic(err)
    }
    */
    
    //fmt.Println(reflect.TypeOf(db))
    //fmt.Println(reflect.TypeOf(result))
    /*
    // Чтение данных
    rows, err := db.Query("select * from users_table")
    if err != nil {
        panic(err)
    }
    
    defer rows.Close()
    dataList := []data{}
    
    for rows.Next(){
        p := data{}
        err := rows.Scan(&p.id, &p.user_name, &p.password, &p.user_info)
        if err != nil{
            fmt.Println(err)
            continue
        }
        dataList = append(dataList, p)
    }
    
    for _, p := range dataList{
        fmt.Println(p.id, p.user_name, p.password, p.user_info)
    }
    
}
*/
























